name: ci

on:
  push:
    # branches: [master]  # TODO RESTORE
  pull_request: # run on all PRs, not just PRs to a particular branch

jobs:
#   unit:
#     strategy:
#       matrix:
#         os: [ubuntu-latest, windows-latest, macos-latest]
#     runs-on: ${{ matrix.os }}

#     steps:
#     - name: git clone
#       uses: actions/checkout@v2
#       with:
#         # Depth of at least 2 for codecov coverage diffs. See https://github.com/GoogleChrome/lighthouse/pull/12079
#         fetch-depth: 2
#     - run: cpanm --notest Test::Perl::Critic Perl::Critic::Freenode
#     - run: perlcritic -1 -q --theme freenode diff-so-fancy
#     - run: ./test/bats/bin/bats test

  perls:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        perl: [ 'blead', 'dev', '5.30', ] # '5.28', '5.26', '5.24', '5.22', '5.20', '5.18', '5.14' ]
    name: Perl ${{ matrix.perl }}
    steps:
      - uses: actions/checkout@v2
      - run: git submodule sync
      - run: git submodule update --init

      - name: Set up perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl }}
          install-modules-with: cpanm
          install-modules: |
            Test::Perl::Critic
            Perl::Critic::Freenode
      - run: perl -V
      - run: perlcritic -1 -q --theme freenode diff-so-fancy
      - run: ./test/bats/bin/bats test